== PP-Module for Email Clients

== This is the correct version to use. The "emailclient" repo is deprecated.

[cols="1,1,1,1,1,1,1,1"]
|===
8+|emailclient 
| https://github.com/commoncriteria/email-client/tree/release-1.0[release-1.0] 
a| https://commoncriteria.github.io/email-client/release-1.0/email-client-release.html[📄]
a|[link=https://github.com/commoncriteria/email-client/blob/gh-pages/release-1.0/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/email-client/gh-pages/release-1.0/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/email-client/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/email-client/gh-pages/release-1.0/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/email-client/blob/gh-pages/release-1.0/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/email-client/gh-pages/release-1.0/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/email-client/blob/gh-pages/release-1.0/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/email-client/gh-pages/release-1.0/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/email-client/gh-pages/release-1.0/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/email-client/blob/gh-pages/release-1.0/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/email-client/gh-pages/release-1.0/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/email-client/blob/gh-pages/release-1.0/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/email-client/gh-pages/release-1.0/pdf_count.svg[PDF Count]
|===

https://github.com/commoncriteria/email-client/issues[image:https://img.shields.io/github/issues/commoncriteria/email-client.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the Protection Profile Module for Email Clients based on the 
[Essential Security Requirements (ESR)](https://commoncriteria.github.io/pp/email-client/email-client-esr.html) for this technology class of 
products. This repository is used to facilitate collaboration and development on the draft document. 
See the [release](#Release-Version) section if you are looking for the officially released version for evaluations. 
A list of products that have passed evaluation against this Protection Profile can be found [here](https://www.niap-ccevs.org/Profile/Info.cfm?id=377).

## Release Version in Github

* [Protection Profile Module for Email Clients (master branch)](https://commoncriteria.github.io/email-client/release-1.0/email-client-release.html) (html)
* [Protection Profile Module for Email Clients (master branch)](https://commoncriteria.github.io/email-client/release-1.0/email-client-release.html.pdf) (pdf)

## Release Version
* [Protection Profile Module for Email Clients](https://www.niap-ccevs.org/Profile/Info.cfm?id=377)

## Contributing

If you are interested in contributing directly to future versions the this Protection Profile, please consider joining the NIAP technical community.
* [How to join the NIAP Technical Community (Mailing list and updates)](https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm)

## Feedback

Questions, comments, and fixes can be submitted to the [repository issue tracker](https://github.com/commoncriteria/email-client/issues)

## Links 
* [National Information Assurance Partnership (NIAP)](https://www.niap-ccevs.org/)
* [Common Criteria Portal](https://www.commoncriteriaportal.org/)
